<?php


namespace App\Views;

use App\App;
use Core\View;

class Footer extends View
{
    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function render($template_path = ROOT . '/app/templates/footer.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}